name: Voice Assistant CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pyinstaller

      - name: Run tests
        run: pytest

      - name: Build executable
        run: |
          pyinstaller --onefile src/main.py --name "VoiceAssistant"

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: VoiceAssistant
          path: dist/VoiceAssistant
